version: "3.9"

services:
  db:
    image: postgres:15
    container_name: devforum-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: devforum
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: devforum-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  postgres_data: